BuySell.WebUI/Controllers/AdsController.cs
using BouNanny.Contracts.Repositories;
using BouNanny.DAL.Data;
using BouNanny.DAL.Repository;
using BouNanny.Models;
//using BouNanny.WebUI.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BouNanny.WebUI.Controllers
{
    public class AdsController : Controller
    {
        //Main DataContext object to be sent to Repository
        DataContext myDataContext = new DataContext();

        //Create Repositories for DataAccess
        IRepositoryBase<Client> Clients;
        IRepositoryBase<Ad> Ads;
        IRepositoryBase<Level> Levels;
        IRepositoryBase<TimePeriod> TimePeriods;
        IRepositoryBase<Country> Countries;
        IRepositoryBase<State> States;
        IRepositoryBase<City> Cities;
        IRepositoryBase<Image> Images;
        IRepositoryBase<Review> Reviews;

        public AdsController()
        {
            //Create Repositories for DataAccess
            Ads = new AdsRepository(myDataContext);
            Clients = new ClientsRepository(myDataContext);
            Images = new ImagesRepository(myDataContext);
            Levels = new LevelsRepository(myDataContext);
            TimePeriods = new TimePeriodsRepository(myDataContext);
            Countries = new CountriesRepository(myDataContext);
            States = new StatesRepository(myDataContext);
            Cities = new CitiesRepository(myDataContext);
            Reviews = new ReviewsRepository(myDataContext);
        }

        // GET: Ads
        public ActionResult Index()
        {
            //This is the main page for Ads.
            //we will get records from Database into this page.

            //Get All Ads as List
            //Aditionally I only want to get last 12 Ads in Descending Order so as not to bombard the Index Page
            List<Ad> AdsList = Ads.GetAll().OrderByDescending(b => b.PostingTime).Take(12).ToList();

            //There will be many Ads so we created a whole List of AdViewModel
            List<Ad> AdViewModels = new List<Ad>();

            //Now Iterate over this List of Ads to populate AdViewModels List
            foreach (Ad Ad in AdsList)
            {
                //New AdViewModel Object
                Ad AdViewModel = new Ad();

                //populate this object from 
                AdViewModel.ID = Ad.ID;
                AdViewModel.Title = Ad.Title;
                AdViewModel.LevelID = Ad.LevelID;
                AdViewModel.Level = Ad.Level;
                AdViewModel.Age = Ad.Age;
                AdViewModel.Sex = Ad.Sex;
                AdViewModel.TimePeriod = Ad.TimePeriod;
                AdViewModel.TimePeriodID = Ad.TimePeriodID;
                AdViewModel.StartingTime = Ad.StartingTime;
                AdViewModel.Description = Ad.Description;
                AdViewModel.Price = Ad.Price;
                AdViewModel.Country = Ad.Country;
                AdViewModel.CountryID = Ad.CountryID;
                AdViewModel.StateID = Ad.StateID;
                AdViewModel.State = Ad.State;
                AdViewModel.CityID = Ad.CityID;
                AdViewModel.City = Ad.City;
                AdViewModel.ClientID = Ad.ClientID;
                AdViewModel.Client = Ad.Client;

                //For images we will iterate through Images from Database & see which Images belong to this Ad
                //then we will send this Images List to AdViewModel.Images
                //-JUST LEAVE IT- bcz i think this will increase load times. 
                AdViewModel.Images = Ad.Images;

                //Get the reviews from Ads Ads Review relation
                AdViewModel.Reviews = Ad.Reviews;

                //now add this viewmodel in List
                AdViewModels.Add(AdViewModel);
            }

            //Now return this list of AdViewModel to View
            return View(AdViewModels);

        }
        // GET: Ads/Details/5
        public ActionResult Details(int? id)
        {
            //on this page user will be looking for details of a Ad by sending an ID

            //first check if there is any ID given with this page 
            if (id == null)
            {
                //return Bad Request if Ads/Details/ & No ID in URL
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Get the Ad by Given ID
            Ad Ad = Ads.GetByID(id);

            //Check if Ad Exists
            if (Ad == null)
            {
                //if not exists then Show 404 Not found
                return HttpNotFound();
            }

            //if Ad is found then Populate the AdViewModel
            //create an object
            Ad AdViewModel = new Ad();

            //Populate it from Ad Details
            AdViewModel.ID = Ad.ID;
            AdViewModel.Title = Ad.Title;
            AdViewModel.Level = Ad.Level;
            AdViewModel.LevelID = Ad.LevelID;
            AdViewModel.Age = Ad.Age;
            AdViewModel.Sex = Ad.Sex;
            AdViewModel.TimePeriod = Ad.TimePeriod;
            AdViewModel.TimePeriodID = Ad.TimePeriodID;
            AdViewModel.Description = Ad.Description;
            AdViewModel.Price = Ad.Price;
            AdViewModel.Country = Ad.Country;
            AdViewModel.CountryID = Ad.CountryID;
            AdViewModel.State = Ad.State;
            AdViewModel.StateID = Ad.StateID;
            AdViewModel.City = Ad.City;
            AdViewModel.CityID = Ad.CityID;
            AdViewModel.Client = Ad.Client;
            AdViewModel.ClientID = Ad.ClientID;
            AdViewModel.PostingTime = Ad.PostingTime;

            //now for Image we will go back to Images Repository & match AdID there.
            AdViewModel.Images = Images.GetAll().Where(i => i.AdID == Ad.ID).ToList();

            //now for Reviews
            AdViewModel.Reviews = Reviews.GetAll().Where(i => i.AdID == Ad.ID).ToList();

            return View(AdViewModel);
        }

        // GET: Ads/Create
        [Authorize]
        public ActionResult Create()
        {
            //Displaying the form for user to create Ad
            //We have to populate the Create form for those DropDown & User Details like Country, State & City in their already.

            //First get Current User details so we can know about Client
            string CurrentUserName = User.Identity.GetUserName();
            Client client = Clients.GetAll().Where(s => s.Username == CurrentUserName).FirstOrDefault();

            //Create a Model & populate then send it to the View
            Ad AdViewModel = new Ad();
            AdViewModel.CountryID = client.CountryID;
            AdViewModel.Country = client.Country;
            AdViewModel.State = client.State;
            AdViewModel.StateID = client.StateID;
            AdViewModel.City = client.City;
            AdViewModel.CityID = client.CityID;
            AdViewModel.Client = client;
            AdViewModel.ClientID = client.ID;

            //Populate Lists in ViewModel to be shown on View
            AdViewModel.LevelsList = Levels.GetAll();
            AdViewModel.TimePeriodsList = TimePeriods.GetAll();
            AdViewModel.CountriesList = Countries.GetAll();
            AdViewModel.StatesList = States.GetAll().Where(c => c.CountryID == client.CountryID);
            AdViewModel.CitiesList = Cities.GetAll().Where(c => c.StateID == client.StateID);

            return View(AdViewModel);
        }
        // POST: Ads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID,Title,LevelID,Age,Sex,StartingTime,SelectedLevelID,TimePeriodID,Description,Price,CountryID,StateID,CityID")] Ad AdViewModel, HttpPostedFileBase ImageFile)
        {
            //User has submitted the Create Form with AdViewModel details & maybe ImageFile
            //We have to get the details from AdViewModel into Ad, Ad & Image Models

            if (ModelState.IsValid)
            {
                //New Ad Object to be populated & then Added into Repository
                Ad ad = new Ad();

                //populate this Ad Object
                ad.Title = AdViewModel.Title;
                ad.TimePeriodID = AdViewModel.TimePeriodID;
                ad.Description = AdViewModel.Description;
                ad.Price = AdViewModel.Price;
                ad.CountryID = AdViewModel.CountryID;
                ad.StateID = AdViewModel.StateID;
                ad.CityID = AdViewModel.CityID;
                ad.LevelID = AdViewModel.LevelID;
                ad.Age = AdViewModel.Age;
                ad.Sex = AdViewModel.Sex;
                ad.ID = ad.ID;

                //Get Current User Details to be send as Client Details in Ad Object
                string CurrentUserName = User.Identity.GetUserName();
                ad.ClientID = Clients.GetAll().Where(s => s.Username == CurrentUserName).FirstOrDefault().ID;

                ad.Slug = AdViewModel.Title.Replace(' ', '-');
                ad.PostingTime = DateTime.Now;

                //Now Add this ad object in our Ads Repository
                Ads.Insert(ad);
                Ads.Commit();

                //Now Check if user has submitted a legal Image file
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    //We have to store this image in our Database as Image Path & then save it in our Images table with AdID

                    //Get Image Path
                    var uploadDir = "~/images";
                    var NewImageName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(ImageFile.FileName);

BuySell.WebUI/Controllers/ProfileController.cs
using BouNanny.DAL.Data;
using BouNanny.Models;
using Microsoft.AspNet.Identity;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace BouNanny.WebUI.Controllers
{
    public class ProfileController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Profile/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //instead of showing him bad request, why not show user, his own profile :D
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                string CurrentUserName = User.Identity.GetUserName();
                id = db.Clients.Where(s => s.Username == CurrentUserName).FirstOrDefault().ID;

                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }

            return View(client);
        }

        // GET: Profile/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.Cities.Where(s => s.StateID == client.StateID), "ID", "Name", client.CityID);
            ViewBag.CountryID = new SelectList(db.Countries, "ID", "Name", client.CountryID);
            ViewBag.StateID = new SelectList(db.States.Where(s => s.CountryID == client.CountryID), "ID", "Name", client.StateID);
            return View(client);
        }

        // POST: Profile/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Email,Username,Name,CountryID,StateID,CityID,MobileNumber,JoinDate")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details");
            }
            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name", client.CityID);
            ViewBag.CountryID = new SelectList(db.Countries, "ID", "Name", client.CountryID);
            ViewBag.StateID = new SelectList(db.States, "ID", "Name", client.StateID);
            return View(client);
        }

        // GET: Profile/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Profile/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BuySell.WebUI/Views/Shared/_AdControlReviewPartial.cshtml
@model BouNanny.WebUI.Models.AdViewModel

@if (Request.IsAuthenticated)
{
    if (@Model.Client.Username == User.Identity.GetUserName())
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Control Your Ad</h3>
            </div>
            <div class="panel-body">
                <div class="form-actions no-color">
                    <div class="col-md-4">
                        @using (Html.BeginForm("Edit", "Ads", new { Id = @Model.ID }, FormMethod.Get))
                        {
                            <input type="submit" name="action" value="Edit" class="col-md-12 btn btn-warning" />
                        }
                    </div>
                    <div class="col-md-4">
                        @using (Html.BeginForm("Delete", "Ads", new { Id = @Model.ID }, FormMethod.Get))
                        {
                            <input type="submit" name="action" value="Delete" class="col-md-12 btn btn-danger" />
                        }
                    </div>
                </div>
            </div>
        </div>
    }
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Add Review</h3>
    </div>
    <div class="panel-body">
        @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("AddReview", "Ads", new { Id = @Model.ID }, FormMethod.Post))
                {
                @Html.AntiForgeryToken()
                <div class="col-md-12 form-group">
                    <div class="form-group">
                        @Html.TextAreaFor(model => model.Review, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4 form-group">
                    <div>
                        <input type="submit" value="Add Your Review" class="col-md-12 btn btn-success" />
                    </div>
                </div>
            }
        }
        else
        {
            using (Html.BeginForm("Login", "Account", new { returnUrl = Url.Encode(Request.RawUrl) }, FormMethod.Get))
            {
                <div class="col-md-4 form-group">
                    <div>
                        <input type="submit" value="Login to Leave Review." class="col-md-12 btn btn-success" />
                    </div>
                </div>
            }
        }
    </div>
</div>

BuySell.WebUI/Views/Shared/_CategoriesPartial.cshtml
<div class="col-md-3">
    <div class="list-group">
        @Html.ActionLink("All offers", "Index", "Ads", null, htmlAttributes: new { @class = "list-group-item" })
    </div>
</div>

BuySell.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BouNanny</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Main Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    
                    @if (User.IsInRole("Admin,Manager"))
                    {
                        <li>@Html.ActionLink("Admin Dashboard", "Index", "Home", new { area = "Dashboard" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
	<div class="container body-content">
		@RenderBody()
	</div>
	<hr />
	<footer>
		<p>&copy; @DateTime.Now.Year - BouNanny</p>
	</footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BuySell.WebUI/Views/Shared/_ProfileControlPartial.cshtml
@model BouNanny.Models.Client

@if (Request.IsAuthenticated)
{
    if (@Model.Username == User.Identity.GetUserName())
    {
        <div class="col-md-8">
            <div class="col-md-4">
                @using (Html.BeginForm("Edit", "Profile", new { Id = @Model.ID }, FormMethod.Get))
                {
                    <input type="submit" name="action" value="Edit" class="col-md-12 btn btn-default" />
                }
            </div>
            <div class="col-md-4">
                @using (Html.BeginForm("Delete", "Profile", new { Id = @Model.ID }, FormMethod.Get))
                {
                    <input type="submit" name="action" value="Delete" class="col-md-12 btn btn-default" />
                }
            </div>
        </div>
    }
}

BuySell.WebUI/Views/Shared/_ReviewsPartial.cshtml
@{
    var ReviewsList = Model.Reviews;

    if (ReviewsList.Count != 0)
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Reviews</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12 well">
                    @foreach (var Review in ReviewsList)
                    {
                        string ReviewerName = Review.Client.Name;
                        int ReviewerID = Review.Client.ID;
                        <div class="row">
                            <div class="col-md-12">
                                <span class="glyphicon glyphicon-user"></span> <b>@Html.ActionLink(ReviewerName, "Details", "Profile", new { area = "", id = ReviewerID }, new { target = "_blank" })</b>
                                <span class="pull-right">Timestamp: <b>@Review.PostingTime</b></span>
                                <br />
                                <p>@Review.Content</p>
                            </div>
                        </div>
                        <hr>
                    }
                 </div>
            </div>
        </div>
    }
}